language: objective-c
before_install:
    - gem install cocoapods
    - pod install --project-directory=Example
    - brew update
    - brew install xctool
script: xctool -workspace Example/DORDoneHUD.xcworkspace -scheme DORDoneHUD-Example test
