language: objective-c
before_install:
    - gem install cocoapods
    - pod install --project-directory=Example
script: xctool -workspace Example/DORDoneHUD.xcworkspace -scheme DORDoneHUD-Example test
