language: objective-c
script:
- set -o pipefail && xcodebuild test -workspace Example/DORDoneHUD.xcworkspace -scheme DORDoneHUD-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
